#pragma once

#define AUXILIARY_STRINGIZING(...)      #__VA_ARGS__
#define AUXILIARY_MAKE_STRING(...)      AUXILIARY_STRINGIZING(__VA_ARGS__)
#define AUXILIARY_FILE_LINE             __FILE__ ":" AUXILIARY_MAKE_STRING(__LINE__)

#define AUXILIARY_ACTUALLY_JOIN(x, y)   x##y
#define AUXILIARY_JOIN(x, y)            AUXILIARY_ACTUALLY_JOIN(x, y)

#ifdef __COUNTER__
#   define AUXILIARY_UNIQUE_VARNAME(x)  AUXILIARY_JOIN(x, __COUNTER__)
#else
#   define AUXILIARY_UNIQUE_VARNAME(x)  AUXILIARY_JOIN(x, __LINE__)
#endif

#define MAKE_UTF8(x)	AUXILIARY_JOIN(u8, AUXILIARY_MAKE_STRING(x))
#define MAKE_UTF16(x)	AUXILIARY_JOIN(u, AUXILIARY_MAKE_STRING(x))
#define MAKE_UTF32(x)	AUXILIARY_JOIN(U, AUXILIARY_MAKE_STRING(x))
#define MAKE_WCHAR(x)	AUXILIARY_JOIN(L, AUXILIARY_MAKE_STRING(x))
